// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbex7Hm-st7f9UX0NOPF9vTHhOMN_JoQk',
    appId: '1:310502233711:web:03aa6aac3b91254f4c1f9a',
    messagingSenderId: '310502233711',
    projectId: 'end-of-a-day-f0e4b',
    authDomain: 'end-of-a-day-f0e4b.firebaseapp.com',
    storageBucket: 'end-of-a-day-f0e4b.firebasestorage.app',
    measurementId: 'G-SWJBB0BR3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQrJ60fd-bBTYqITlx1yuIreJ4MNoPun0',
    appId: '1:310502233711:android:87aa203fbf3999da4c1f9a',
    messagingSenderId: '310502233711',
    projectId: 'end-of-a-day-f0e4b',
    storageBucket: 'end-of-a-day-f0e4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcLKYhqcZ_AL9UOktm41avfxxy9MnsSxs',
    appId: '1:310502233711:ios:5139e1795746c8154c1f9a',
    messagingSenderId: '310502233711',
    projectId: 'end-of-a-day-f0e4b',
    storageBucket: 'end-of-a-day-f0e4b.firebasestorage.app',
    iosBundleId: 'com.inu.endofaday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcLKYhqcZ_AL9UOktm41avfxxy9MnsSxs',
    appId: '1:310502233711:ios:892e259da723f36f4c1f9a',
    messagingSenderId: '310502233711',
    projectId: 'end-of-a-day-f0e4b',
    storageBucket: 'end-of-a-day-f0e4b.firebasestorage.app',
    iosBundleId: 'inu.flutter.endofaday.endOfADay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbex7Hm-st7f9UX0NOPF9vTHhOMN_JoQk',
    appId: '1:310502233711:web:166051ed5f4a2dc94c1f9a',
    messagingSenderId: '310502233711',
    projectId: 'end-of-a-day-f0e4b',
    authDomain: 'end-of-a-day-f0e4b.firebaseapp.com',
    storageBucket: 'end-of-a-day-f0e4b.firebasestorage.app',
    measurementId: 'G-0B6TSBX8DE',
  );
}
